// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSvlYLs085e1_Tdo1QkEClcFdBkucyAhs',
    appId: '1:463810911372:web:960e74033b41945281efa9',
    messagingSenderId: '463810911372',
    projectId: 'personal-expense-tracker-fac4f',
    authDomain: 'personal-expense-tracker-fac4f.firebaseapp.com',
    storageBucket: 'personal-expense-tracker-fac4f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv5DL3rkPOBg2O6OThC5pqzeKnxbiR8fs',
    appId: '1:463810911372:android:05dbed507975b72c81efa9',
    messagingSenderId: '463810911372',
    projectId: 'personal-expense-tracker-fac4f',
    storageBucket: 'personal-expense-tracker-fac4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJFSCtN8SSSztTn0-nHGT73pYbOr9xfLA',
    appId: '1:463810911372:ios:158f851846f5bb5c81efa9',
    messagingSenderId: '463810911372',
    projectId: 'personal-expense-tracker-fac4f',
    storageBucket: 'personal-expense-tracker-fac4f.appspot.com',
    androidClientId: '463810911372-gosias341v8helclrs4cb9nb9cnbb334.apps.googleusercontent.com',
    iosClientId: '463810911372-4v21pp9mq4grp4jrhc177q5hog3c2sqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.clickCounter',
  );
}
